### ISSUE TITLE
aix_etchosts("delete all entries") fails if  /etc/hosts is already empty. Should be a no-op

### ISSUE THREAD

**Issue by jkohlmeier** [chef-cookbooks/aix#77]
### Cookbook version
aix 1.2.1
### Chef-client version
 version 12.14.89

### Platform Details
Aix 7.2 TL1
### Scenario:
Was working on building etc/hosts from scratch. 

### Steps to Reproduce:
aix_etchosts "delete all entries" do
  action :delete_all
end

just run it twice, without adding to /etc/hosts.

### Expected Result:
should be a no-op.

### Actual Result:
Errors with exit value of 1. should be 0.

**Comment by iennae** [comment]
Thanks for reporting.

**Comment by msgarbossa** [comment]
I don't have a use case for "delete all entries".  That being said, clobbering the file with a simple execute resource would work too, but it would also remove the headers.  The aix_etchosts resource is relying on the hostent command, which is AIX specific.  For the few /etc/hosts entries I'm dealing with, I like [hostsfile](https://github.com/customink-webops/hostsfile).  It is more cross-platform since it just deals with the hosts file as a regular text file.  It also seems better maintained by Chef since it is easier to test without having an AIX box.  I try not to make AIX any more special than it already is.

According to the man page for hostent:

> The hostent low-level command adds, deletes, or changes address-mapping entries in the system configuration database. Entries in the database are used to map an Internet Protocol (IP) address (local or remote) to its equivalent host names.

I still don't see what it's doing besides being an abstraction for managing /etc/hosts, which is what the hostsfile cookbook also accomplishes.  Preferring to just "vi files", I've never used the hostent command.

**Comment by iennae** [comment]
@jkohlmeier please check out version 2.1.0 of the cookbook. Thanks to @msgarbossa this should be resolved.
